export const Data = [
  {
    id: 1,
    img: "/images/Illustrations/AveriePatch/",
    alt: "Averie Patch Project",
    title: "Averie Patch Project",
    link: "/illustrations/averie-patch",
    caption:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
    description:
      "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
    images: [
      { img: "/images/Illustrations/AveriePatch/cover.jpg", alt: "" },
      { img: "/images/Illustrations/AveriePatch/1.jpg", alt: "" },
      { img: "/images/Illustrations/AveriePatch/2.jpg", alt: "" },
      { img: "/images/Illustrations/AveriePatch/3.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/4.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/5.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/6.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/7.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/8.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/9.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/10.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/11.jpg", alt: "" },
      { img: "/images/Illustrations/AveriePatch/12.jpg", alt: "" },
      { img: "/images/Illustrations/AveriePatch/13.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/14.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/15.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/16.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/17.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/18.jpg", alt: "" },
      { img: "/images/Illustrations/AveriPatch/19.jpg", alt: "" },
    ],
  },
  {
    id: 2,
    img: "/images/Illustrations/Book1/",
    alt: "book",
    title: "The Daily Routine of My Cat Book",
    link: "/illustrations/the-daily-routine-of-my-cat",
    caption:
      "A set of travel stickers for Steamline Luggage, a luxury vintage suitcase maker.",
    description:
      "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
    images: [
      { img: "/images/Illustrations/Book1/cover.jpg", alt: "" },
      { img: "/images/Illustrations/Book1/1.jpg", alt: "" },
      { img: "/images/Illustrations/Book1/2.jpg", alt: "" },
      { img: "/images/Illustrations/Book1/3.jpg", alt: "" },
      { img: "/images/Illustrations/Book1/4.jpg", alt: "" },
      { img: "/images/Illustrations/Book1/5.jpg", alt: "" },
    ],
  },
  {
    id: 3,
    img: "/images/Illustrations/Book2/",
    alt: "book",
    title: "The Habits and Lifestyles of Happy People Book",
    link: "/illustrations/the-habits-and-lifestyles-of-happy-people",
    caption:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
    description:
      "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
    images: [
      { img: "/images/Illustrations/Book2/cover.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/1.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/2.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/3.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/4.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/5.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/6.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/7.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/8.jpg", alt: "" },
      { img: "/images/Illustrations/Book2/9.jpg", alt: "" },
    ],
  },
  {
    id: 4,
    img: "/images/Illustrations/Instagram/",
    alt: "instagram project",
    title: "@eln.draws",
    caption: "An archive of my Illustrations and doodles",
    link: "/illustrations/eln-draws-instagram",
    description:
      "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
    images: [
      { img: "/images/Illustrations/Instagram/cover.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/1.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/2.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/3.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/4.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/5.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/6.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/7.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/8.jpg", alt: "" },
      { img: "/images/Illustrations/Instagram/9.jpg", alt: "" },
    ],
  },
];
