export const Data = [
  {
    id: 1,
    name: "branding",
    document: [
      {
        id: 1,
        img: "/images/Branding/KopiCat/",
        alt: "Kopi Cat",
        title: "Kopi Cat",
        caption:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",

        link: "/branding/kopi-cat",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Branding/KopiCat/cover.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/1.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/2.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/3.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/4.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/5.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/6.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/7.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/8.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/9.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/10.jpg", alt: "" },
          { img: "/images/Branding/KopiCat/11.jpg", alt: "" },
        ],
      },
      {
        id: 2,
        img: "/images/Branding/Mamake/",
        alt: "Mamake",
        title: "Mamake",
        caption:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
        link: "/branding/mamake",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Branding/Mamake/cover.jpg", alt: "" },
          { img: "/images/Branding/Mamake/1.jpg", alt: "" },
          { img: "/images/Branding/Mamake/2.jpg", alt: "" },
          { img: "/images/Branding/Mamake/3.jpg", alt: "" },
        ],
      },
      {
        id: 3,
        img: "/images/Branding/Pyramid/",
        alt: "",
        title: "Pyramid Coconut Oil",
        caption:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
        link: "/branding/pyramid-coconut-oil",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Branding/Pyramid/cover.jpg", alt: "" },
          { img: "/images/Branding/Pyramid/4.jpg", alt: "" },
          { img: "/images/Branding/Pyramid/5.jpg", alt: "" },
          { img: "/images/Branding/Pyramid/3.jpg", alt: "" },
          { img: "/images/Branding/Pyramid/2.jpg", alt: "" },
          { img: "/images/Branding/Pyramid/1.jpg", alt: "" },
        ],
      },
      {
        id: 4,
        img: "/images/Branding/Roteri/",
        alt: "",
        title: "Roteri",
        caption:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
        link: "/branding/roteri",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Branding/Roteri/cover.jpg", alt: "" },
          { img: "/images/Branding/Roteri/1.jpg", alt: "" },
          { img: "/images/Branding/Roteri/2.jpg", alt: "" },
          { img: "/images/Branding/Roteri/3.jpg", alt: "" },
          { img: "/images/Branding/Roteri/4.jpg", alt: "" },
          { img: "/images/Branding/Roteri/5.jpg", alt: "" },
          { img: "/images/Branding/Roteri/6.jpg", alt: "" },
        ],
      },
      {
        id: 5,
        img: "/images/Branding/JungleFlorist/",
        alt: "",
        title: "Jungle Florist Rebranding",
        caption:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
        link: "/branding/jungle-florist-rebranding",
        images: [
          { img: "/images/Branding/JungleFlorist/cover.jpg", alt: "" },
          { img: "/images/Branding/JungleFlorist/1.jpg", alt: "" },
          { img: "/images/Branding/JungleFlorist/2.jpg", alt: "" },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "illustrations",
    document: [
      {
        id: 1,
        img: "/images/Illustrations/AveriePatch/",
        alt: "Averie Patch Project",
        title: "Averie Patch",
        link: "/illustrations/averie-patch-project",
        caption:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Illustrations/AveriePatch/cover.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/1.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/2.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/3.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/4.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/5.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/6.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/7.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/8.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/9.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/10.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/11.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/12.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/13.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/14.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/15.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/16.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/17.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/18.jpg", alt: "" },
          { img: "/images/Illustrations/AveriePatch/19.jpg", alt: "" },
        ],
      },
      {
        id: 2,
        img: "/images/Illustrations/Book1/",
        alt: "book",
        title: "The Daily Routine of My Cat",
        link: "/illustrations/the-daily-routine-of-my-cat",
        caption:
          "A set of travel stickers for Steamline Luggage, a luxury vintage suitcase maker.",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Illustrations/Book1/cover.jpg", alt: "" },
          { img: "/images/Illustrations/Book1/1.jpg", alt: "" },
          { img: "/images/Illustrations/Book1/2.jpg", alt: "" },
          { img: "/images/Illustrations/Book1/3.jpg", alt: "" },
          { img: "/images/Illustrations/Book1/4.jpg", alt: "" },
          { img: "/images/Illustrations/Book1/5.jpg", alt: "" },
        ],
      },
      {
        id: 3,
        img: "/images/Illustrations/Book2/",
        alt: "book",
        title: "The Habits and Lifestyles of Happy People",
        link: "/illustrations/the-habits-and-lifestyles-of-happy-people",
        caption:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat, molestiae. Blanditiis, enim.",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Illustrations/Book2/cover.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/1.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/2.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/3.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/4.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/5.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/6.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/7.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/8.jpg", alt: "" },
          { img: "/images/Illustrations/Book2/9.jpg", alt: "" },
        ],
      },
      {
        id: 4,
        img: "/images/Illustrations/Instagram/",
        alt: "instagram project",
        title: "Eln Draws Instagram",
        caption: "An archive of my Illustrations and doodles",
        link: "/illustrations/eln-draws-instagram",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Illustrations/Instagram/cover.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/1.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/2.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/3.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/4.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/5.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/6.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/7.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/8.jpg", alt: "" },
          { img: "/images/Illustrations/Instagram/9.jpg", alt: "" },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "layout",
    document: [
      {
        id: 1,
        img: "/images/Layout/Dekornata/",
        alt: "Dekornata",
        title: "Dekornata",
        caption:
          "Godard direct trade drinking vinegar trust fund bushwick pop-up, tattooed vegan.",
        link: "/layout/dekornata",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Layout/Dekornata/cover.jpg", alt: "" },
          { img: "/images/Layout/Dekornata/1.jpg", alt: "" },
          { img: "/images/Layout/Dekornata/2.jpg", alt: "" },
          { img: "/images/Layout/Dekornata/3.jpg", alt: "" },
          { img: "/images/Layout/Dekornata/4.jpg", alt: "" },
          { img: "/images/Layout/Dekornata/5.jpg", alt: "" },
          { img: "/images/Layout/Dekornata/6.jpg", alt: "" },
        ],
      },
      {
        id: 2,
        img: "/images/Layout/Journey/",
        alt: "Journey",
        title: "Journey",
        link: "/layout/journey",
        caption:
          "Whatever palo santo chartreuse snackwave knausgaard, copper mug prism gochujang schlitz post-ironic.",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Layout/Journey/cover.jpg", alt: "" },
          { img: "/images/Layout/Journey/1.jpg", alt: "" },
          { img: "/images/Layout/Journey/2.jpg", alt: "" },
          { img: "/images/Layout/Journey/3.jpg", alt: "" },
          { img: "/images/Layout/Journey/4.jpg", alt: "" },
          { img: "/images/Layout/Journey/5.jpg", alt: "" },
          { img: "/images/Layout/Journey/6.jpg", alt: "" },
          { img: "/images/Layout/Journey/7.jpg", alt: "" },
          { img: "/images/Layout/Journey/8.jpg", alt: "" },
          { img: "/images/Layout/Journey/9.jpg", alt: "" },
          { img: "/images/Layout/Journey/10.jpg", alt: "" },
        ],
      },
      {
        id: 3,
        img: "/images/Layout/Neville/",
        alt: "",
        title: "Neville",
        link: "/layout/neville",
        caption:
          "Pork belly twee swag tumeric kale chips. Street art skateboard brooklyn vegan microdosing.",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Layout/Neville/cover.jpg", alt: "" },
          { img: "/images/Layout/Neville/1.jpg", alt: "" },
          { img: "/images/Layout/Neville/2.jpg", alt: "" },
          { img: "/images/Layout/Neville/3.jpg", alt: "" },
          { img: "/images/Layout/Neville/4.jpg", alt: "" },
          { img: "/images/Layout/Neville/5.jpg", alt: "" },
          { img: "/images/Layout/Neville/6.jpg", alt: "" },
          { img: "/images/Layout/Neville/7.jpg", alt: "" },
        ],
      },
      {
        id: 4,
        img: "/images/Layout/Ragunan/",
        alt: "",
        title: "Ragunan",
        link: "/layout/ragunan",
        caption:
          "Marfa ramps hexagon cred, 3 wolf moon small batch pinterest mlkshk farm-to-table tbh. ",
        description:
          "Copper mug listicle activated charcoal, organic post-ironic gentrify banh mi air plant food truck yr small batch VHS brooklyn letterpress.",
        images: [
          { img: "/images/Layout/Ragunan/cover.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/1.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/2.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/3.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/4.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/5.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/6.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/7.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/8.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/9.jpg", alt: "" },
          { img: "/images/Layout/Ragunan/10.jpg", alt: "" },
        ],
      },
    ],
  },
];
